feat: init monorepo

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,35 +1,54 @@
-name: "units-test"
+name: Test
 on:
   pull_request:
   push:
     branches:
       - main
-      - 'releases/*'
+      - "releases/*"
 
 jobs:
   # unit tests
   units:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        package: [generate-dotenv, deploy-docker-ssh]
     steps:
-    - uses: actions/checkout@v3
-    - run: npm ci
-    - run: npm test
+      - uses: actions/checkout@v3
+      - run: npm ci
+      - run: npm test
 
   # test action works running from the graph
-  test:
+  test-dotenv:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        package: [generate-dotenv, deploy-docker-ssh]
+    steps:
+      - uses: actions/checkout@v3
+      - id: generate-dotenv
+        uses: ./packages/${{ matrix.package }}/
+        with:
+          template-paths: "tests/stubs/_.env"
+      - name: Cache dotenv
+        id: cache-dotenv
+        uses: actions/cache@v3
+        with:
+          path: .env
+          key: ${{ steps.generate-dotenv.outputs.cache-key }}
+      - name: Require cached dotenv file
+        if: steps.cache-dotenv.outputs.cache-hit != 'true'
+        run: echo "Failed to restore cached dotenv file." && exit 1
+
+  test-deploy:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - id: generate-dotenv
-      uses: ./
-      with:
-        template-paths: 'tests/stubs/_.env'
-    - name: Cache dotenv
-      id: cache-dotenv
-      uses: actions/cache@v3
-      with:
-        path: .env
-        key: ${{ steps.generate-dotenv.outputs.cache-key }}
-    - name: Require cached dotenv file
-      if: steps.cache-dotenv.outputs.cache-hit != 'true'
-      run: echo "Failed to restore cached dotenv file." && exit 1
+      - uses: actions/checkout@v3
+      - uses: ./
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          user: jacob
+          target-dir: /tmp
+          ssh-port: ${{ secrets.SSH_PORT }}
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+          command: echo "Hello world."
